/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BungieNetApi.Client.OpenAPIDateConverter;

namespace BungieNetApi.Model
{
    /// <summary>
    /// DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry
    /// </summary>
    [DataContract]
    public partial class DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry :  IEquatable<DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry" /> class.
        /// </summary>
        /// <param name="currencyItemHash">currencyItemHash.</param>
        /// <param name="scalarValue">scalarValue.</param>
        public DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry(long currencyItemHash = default(long), int scalarValue = default(int))
        {
            this.CurrencyItemHash = currencyItemHash;
            this.ScalarValue = scalarValue;
        }
        
        /// <summary>
        /// Gets or Sets CurrencyItemHash
        /// </summary>
        [DataMember(Name="currencyItemHash", EmitDefaultValue=false)]
        public long CurrencyItemHash { get; set; }

        /// <summary>
        /// Gets or Sets ScalarValue
        /// </summary>
        [DataMember(Name="scalarValue", EmitDefaultValue=false)]
        public int ScalarValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry {\n");
            sb.Append("  CurrencyItemHash: ").Append(CurrencyItemHash).Append("\n");
            sb.Append("  ScalarValue: ").Append(ScalarValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry);
        }

        /// <summary>
        /// Returns true if DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry instances are equal
        /// </summary>
        /// <param name="input">Instance of DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CurrencyItemHash == input.CurrencyItemHash ||
                    this.CurrencyItemHash.Equals(input.CurrencyItemHash)
                ) && 
                (
                    this.ScalarValue == input.ScalarValue ||
                    this.ScalarValue.Equals(input.ScalarValue)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.CurrencyItemHash.GetHashCode();
                hashCode = hashCode * 59 + this.ScalarValue.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
