/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BungieNetApi.Client.OpenAPIDateConverter;

namespace BungieNetApi.Model
{
    /// <summary>
    /// Returns data about a character&#39;s status with a given Objective. Combine with DestinyObjectiveDefinition static data for display purposes.
    /// </summary>
    [DataContract]
    public partial class DestinyQuestsDestinyObjectiveProgress :  IEquatable<DestinyQuestsDestinyObjectiveProgress>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DestinyQuestsDestinyObjectiveProgress" /> class.
        /// </summary>
        /// <param name="objectiveHash">The unique identifier of the Objective being referred to. Use to look up the DestinyObjectiveDefinition in static data..</param>
        /// <param name="destinationHash">If the Objective has a Destination associated with it, this is the unique identifier of the Destination being referred to. Use to look up the DestinyDestinationDefinition in static data. This will give localized data about *where* in the universe the objective should be achieved..</param>
        /// <param name="activityHash">If the Objective has an Activity associated with it, this is the unique identifier of the Activity being referred to. Use to look up the DestinyActivityDefinition in static data. This will give localized data about *what* you should be playing for the objective to be achieved..</param>
        /// <param name="progress">If progress has been made, and the progress can be measured numerically, this will be the value of that progress. You can compare it to the DestinyObjectiveDefinition.completionValue property for current vs. upper bounds, and use DestinyObjectiveDefinition.valueStyle to determine how this should be rendered. Note that progress, in Destiny 2, need not be a literal numeric progression. It could be one of a number of possible values, even a Timestamp. Always examine DestinyObjectiveDefinition.valueStyle before rendering progress..</param>
        /// <param name="completionValue">As of Forsaken, objectives&#39; completion value is determined dynamically at runtime.  This value represents the threshold of progress you need to surpass in order for this objective to be considered \&quot;complete\&quot;.  If you were using objective data, switch from using the DestinyObjectiveDefinition&#39;s \&quot;completionValue\&quot; to this value..</param>
        /// <param name="complete">Whether or not the Objective is completed..</param>
        /// <param name="visible">If this is true, the objective is visible in-game. Otherwise, it&#39;s not yet visible to the player. Up to you if you want to honor this property..</param>
        public DestinyQuestsDestinyObjectiveProgress(long objectiveHash = default(long), long destinationHash = default(long), long activityHash = default(long), int progress = default(int), int completionValue = default(int), bool complete = default(bool), bool visible = default(bool))
        {
            this.ObjectiveHash = objectiveHash;
            this.DestinationHash = destinationHash;
            this.ActivityHash = activityHash;
            this.Progress = progress;
            this.CompletionValue = completionValue;
            this.Complete = complete;
            this.Visible = visible;
        }
        
        /// <summary>
        /// The unique identifier of the Objective being referred to. Use to look up the DestinyObjectiveDefinition in static data.
        /// </summary>
        /// <value>The unique identifier of the Objective being referred to. Use to look up the DestinyObjectiveDefinition in static data.</value>
        [DataMember(Name="objectiveHash", EmitDefaultValue=false)]
        public long ObjectiveHash { get; set; }

        /// <summary>
        /// If the Objective has a Destination associated with it, this is the unique identifier of the Destination being referred to. Use to look up the DestinyDestinationDefinition in static data. This will give localized data about *where* in the universe the objective should be achieved.
        /// </summary>
        /// <value>If the Objective has a Destination associated with it, this is the unique identifier of the Destination being referred to. Use to look up the DestinyDestinationDefinition in static data. This will give localized data about *where* in the universe the objective should be achieved.</value>
        [DataMember(Name="destinationHash", EmitDefaultValue=false)]
        public long DestinationHash { get; set; }

        /// <summary>
        /// If the Objective has an Activity associated with it, this is the unique identifier of the Activity being referred to. Use to look up the DestinyActivityDefinition in static data. This will give localized data about *what* you should be playing for the objective to be achieved.
        /// </summary>
        /// <value>If the Objective has an Activity associated with it, this is the unique identifier of the Activity being referred to. Use to look up the DestinyActivityDefinition in static data. This will give localized data about *what* you should be playing for the objective to be achieved.</value>
        [DataMember(Name="activityHash", EmitDefaultValue=false)]
        public long ActivityHash { get; set; }

        /// <summary>
        /// If progress has been made, and the progress can be measured numerically, this will be the value of that progress. You can compare it to the DestinyObjectiveDefinition.completionValue property for current vs. upper bounds, and use DestinyObjectiveDefinition.valueStyle to determine how this should be rendered. Note that progress, in Destiny 2, need not be a literal numeric progression. It could be one of a number of possible values, even a Timestamp. Always examine DestinyObjectiveDefinition.valueStyle before rendering progress.
        /// </summary>
        /// <value>If progress has been made, and the progress can be measured numerically, this will be the value of that progress. You can compare it to the DestinyObjectiveDefinition.completionValue property for current vs. upper bounds, and use DestinyObjectiveDefinition.valueStyle to determine how this should be rendered. Note that progress, in Destiny 2, need not be a literal numeric progression. It could be one of a number of possible values, even a Timestamp. Always examine DestinyObjectiveDefinition.valueStyle before rendering progress.</value>
        [DataMember(Name="progress", EmitDefaultValue=false)]
        public int Progress { get; set; }

        /// <summary>
        /// As of Forsaken, objectives&#39; completion value is determined dynamically at runtime.  This value represents the threshold of progress you need to surpass in order for this objective to be considered \&quot;complete\&quot;.  If you were using objective data, switch from using the DestinyObjectiveDefinition&#39;s \&quot;completionValue\&quot; to this value.
        /// </summary>
        /// <value>As of Forsaken, objectives&#39; completion value is determined dynamically at runtime.  This value represents the threshold of progress you need to surpass in order for this objective to be considered \&quot;complete\&quot;.  If you were using objective data, switch from using the DestinyObjectiveDefinition&#39;s \&quot;completionValue\&quot; to this value.</value>
        [DataMember(Name="completionValue", EmitDefaultValue=false)]
        public int CompletionValue { get; set; }

        /// <summary>
        /// Whether or not the Objective is completed.
        /// </summary>
        /// <value>Whether or not the Objective is completed.</value>
        [DataMember(Name="complete", EmitDefaultValue=false)]
        public bool Complete { get; set; }

        /// <summary>
        /// If this is true, the objective is visible in-game. Otherwise, it&#39;s not yet visible to the player. Up to you if you want to honor this property.
        /// </summary>
        /// <value>If this is true, the objective is visible in-game. Otherwise, it&#39;s not yet visible to the player. Up to you if you want to honor this property.</value>
        [DataMember(Name="visible", EmitDefaultValue=false)]
        public bool Visible { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DestinyQuestsDestinyObjectiveProgress {\n");
            sb.Append("  ObjectiveHash: ").Append(ObjectiveHash).Append("\n");
            sb.Append("  DestinationHash: ").Append(DestinationHash).Append("\n");
            sb.Append("  ActivityHash: ").Append(ActivityHash).Append("\n");
            sb.Append("  Progress: ").Append(Progress).Append("\n");
            sb.Append("  CompletionValue: ").Append(CompletionValue).Append("\n");
            sb.Append("  Complete: ").Append(Complete).Append("\n");
            sb.Append("  Visible: ").Append(Visible).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DestinyQuestsDestinyObjectiveProgress);
        }

        /// <summary>
        /// Returns true if DestinyQuestsDestinyObjectiveProgress instances are equal
        /// </summary>
        /// <param name="input">Instance of DestinyQuestsDestinyObjectiveProgress to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DestinyQuestsDestinyObjectiveProgress input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ObjectiveHash == input.ObjectiveHash ||
                    this.ObjectiveHash.Equals(input.ObjectiveHash)
                ) && 
                (
                    this.DestinationHash == input.DestinationHash ||
                    this.DestinationHash.Equals(input.DestinationHash)
                ) && 
                (
                    this.ActivityHash == input.ActivityHash ||
                    this.ActivityHash.Equals(input.ActivityHash)
                ) && 
                (
                    this.Progress == input.Progress ||
                    this.Progress.Equals(input.Progress)
                ) && 
                (
                    this.CompletionValue == input.CompletionValue ||
                    this.CompletionValue.Equals(input.CompletionValue)
                ) && 
                (
                    this.Complete == input.Complete ||
                    this.Complete.Equals(input.Complete)
                ) && 
                (
                    this.Visible == input.Visible ||
                    this.Visible.Equals(input.Visible)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.ObjectiveHash.GetHashCode();
                hashCode = hashCode * 59 + this.DestinationHash.GetHashCode();
                hashCode = hashCode * 59 + this.ActivityHash.GetHashCode();
                hashCode = hashCode * 59 + this.Progress.GetHashCode();
                hashCode = hashCode * 59 + this.CompletionValue.GetHashCode();
                hashCode = hashCode * 59 + this.Complete.GetHashCode();
                hashCode = hashCode * 59 + this.Visible.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
