/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BungieNetApi.Client.OpenAPIDateConverter;

namespace BungieNetApi.Model
{
    /// <summary>
    /// Represents a data-driven view for Email settings. Web/Mobile UI can use this data to show new EMail settings consistently without further manual work.
    /// </summary>
    [DataContract]
    public partial class UserEmailViewDefinition :  IEquatable<UserEmailViewDefinition>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserEmailViewDefinition" /> class.
        /// </summary>
        /// <param name="name">The identifier for this view..</param>
        /// <param name="viewSettings">The ordered list of settings to show in this view..</param>
        public UserEmailViewDefinition(string name = default(string), List<UserEmailViewDefinitionSetting> viewSettings = default(List<UserEmailViewDefinitionSetting>))
        {
            this.Name = name;
            this.ViewSettings = viewSettings;
        }
        
        /// <summary>
        /// The identifier for this view.
        /// </summary>
        /// <value>The identifier for this view.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// The ordered list of settings to show in this view.
        /// </summary>
        /// <value>The ordered list of settings to show in this view.</value>
        [DataMember(Name="viewSettings", EmitDefaultValue=false)]
        public List<UserEmailViewDefinitionSetting> ViewSettings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserEmailViewDefinition {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ViewSettings: ").Append(ViewSettings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserEmailViewDefinition);
        }

        /// <summary>
        /// Returns true if UserEmailViewDefinition instances are equal
        /// </summary>
        /// <param name="input">Instance of UserEmailViewDefinition to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserEmailViewDefinition input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.ViewSettings == input.ViewSettings ||
                    this.ViewSettings != null &&
                    input.ViewSettings != null &&
                    this.ViewSettings.SequenceEqual(input.ViewSettings)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.ViewSettings != null)
                    hashCode = hashCode * 59 + this.ViewSettings.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
